
/*--------SHEMA BDD--------*/

CREATE TABLE user_app(
user_id VARCHAR(150) NOT NULL UNIQUE PRIMARY KEY,
first_name VARCHAR(100) NOT NULL,
last_name VARCHAR(100) NOT NULL,
password VARCHAR(100) NOT NULL,
role VARCHAR(10) 
);

CREATE TABLE contacts (
 id_contact VARCHAR(150) NOT NULL  ,
user_id VARCHAR(150) NOT NULL,
  PRIMARY KEY ( id_contact,user_id),
  FOREIGN KEY ( id_contact) REFERENCES user_app(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
 FOREIGN KEY (user_id ) REFERENCES user_app(user_id) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE account(
id BIGINT NOT NULL AUTO_INCREMENT,
user_id VARCHAR(150)   NOT NULL,
balance DECIMAL NOT NULL,
account_type VARCHAR(15) NOT NULL,
creation DATETIME NOT NULL,
FOREIGN KEY(user_id) REFERENCES user_app(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
PRIMARY KEY(id,user_id )
);

ALTER TABLE account AUTO_INCREMENT = 76001;

CREATE TABLE transaction(
transaction_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
transaction_date_time DATETIME NOT NULL,
credit_user_id VARCHAR(150) NOT NULL,
beneficiary_user_id VARCHAR(150) NOT NULL,
description VARCHAR(250) NOT NULL,
amount DECIMAL NOT NULL,
transaction_fees FLOAT NOT NULL,
FOREIGN KEY(credit_user_id) REFERENCES account(user_id) ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY(beneficiary_user_id) REFERENCES account(user_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

ALTER TABLE transaction AUTO_INCREMENT = 1001;


